### ISSUE TITLE
Users not accessed by GET route

### ISSUE THREAD

**Issue by brianjeball** [brianjeball/Project-9-Treehouse#1]
User created in **POST** route should be saved in **users** array.

> Index.js: line 136

GET route for users cannot access users in the array.

> Index.js: line 35

Error message recieved when testing GET route (**GET /api/users**) in Postman

`{"message":"Cannot read property 'username' of undefined",
"stack":"TypeError: Cannot read property 'username' of undefined\n at users.find.u (/Users/brianjball/Desktop/Codes/Project-9-Treehouse/routes/index.js:35:38)\n at Array.find ()\n at authenticateUser (/Users/brianjball/Desktop/Codes/Project-9-Treehouse/routes/index.js:35:26)\n at Layer.handle [as handle_request] `

**Comment by brianjeball** [comment]
Data in the body of the request not parsed. 
**FIXED: Missing Body-Parser module**
